# Generated by Django 5.0.6 on 2024-06-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_options_profile_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('User VIP', 'VIP пользователь'), ('User', 'Пользователь'), ('Admin', 'Администратор')], default='User', max_length=20, verbose_name='Статус пользователя'),
        ),
    ]
