# Generated by Django 5.0.6 on 2024-07-05 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('User', 'Пользователь'), ('Admin', 'Администратор'), ('User VIP', 'VIP пользователь')], default='User', max_length=20, verbose_name='Статус пользователя'),
        ),
    ]
