# Generated by Django 5.0.6 on 2024-06-19 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_alter_article_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Category №1', 'Рубрика №1'), ('Category №2', 'Рубрика №2'), ('Category №3', 'Рубрика №3'), ('Category №4', 'Рубрика №4'), ('Category №5', 'Рубрика №5')], default='Рубрика №1', max_length=50, verbose_name='Рубрика'),
        ),
    ]
