# Generated by Django 5.0.6 on 2024-06-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_alter_like_options_alter_like_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Category №1', 'Физика'), ('Category №2', 'Астрономия'), ('Category №3', 'Математика'), ('Category №4', 'Химия'), ('Category №5', 'Биология')], default='Физика', max_length=50, verbose_name='Рубрика'),
        ),
    ]
