# Generated by Django 5.0.6 on 2024-07-05 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0011_alter_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.ImageField(default='default_preview.png', upload_to='preview_images', verbose_name='Превью'),
        ),
    ]
