# Generated by Django 5.0.6 on 2024-07-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0013_alter_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Analytics', 'Аналитика'), ('ART', 'АРТ'), ('Music', 'Музыка'), ('Science', 'Наука'), ('Varial', 'Разное')], default='Разное', max_length=50, verbose_name='Рубрика'),
        ),
    ]
