# Generated by Django 5.0.6 on 2024-07-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0015_alter_article_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
